
[workspace]
resolver = "2"
members = ["cli", "clients/rust", "program"]

[workspace.dependencies]
yellowstone-blocklist-client = { path = "clients/rust" }
yellowstone-blocklist = { path = "program" }
anyhow = "1.0.97"
