[workspace]
resolver = "2"
members = ["parser", "program", "store", "clients/rust", "cli"]

[workspace.package]
version = "0.6.0"

[workspace.dependencies]
anyhow = "1.0.97"
anchor-lang = "0.31.0"
arc-swap = "1.6.0"
assert_matches = "1.5.0"
async-trait = "0.1.88"
borsh = "1.0.0"
bs58 = "0.5.1"
bytemuck = "1.24.0"
clap = "4.5.50"
clap_derive = "4.5.32"
env_logger = "0.11.3"
futures = "0.3.0"
hashbrown = "0.16.0"
log = "0.4.21"
num-derive = "0.4.2"
num-traits = "0.2.0"
parking_lot = "0.12.5"
pinocchio = "0.9.2"
pinocchio-system = "0.3.0"
pinocchio-pubkey = "0.3.0"
serde = "1.0.0"
serde_json = "1.0.117"
serde_with = "3.0.0"
shank = "0.4.2"
# Solana SDK (decoupled from Agave)
# See: https://github.com/anza-xyz/solana-sdk
solana-pubkey = "3"
solana-transaction = { version = "3", features = ["bincode"] }
solana-instruction = "3"
solana-commitment-config = "3"
solana-keypair = "3"
solana-message = "3"
solana-msg = "3"
solana-signer = "3"
solana-rent = "3"
solana-program = "3"
solana-program-entrypoint = "3"
solana-account-info = "3"
solana-program-error = "3"
solana-decode-error = "2.3"
solana-system-interface = "2.0.0"
solana-cpi = "3"
# Agave Crates
solana-hash = "3"
solana-cli-config = "3"
solana-client = "3"
solana-account-decoder-client-types = "3"
solana-program-test = "3"
# Solana misc
spl-associated-token-account-interface = "2.0.0"
spl-pod = "0.7.1"
spl-token = "9.0.0"
spl-token-group-interface = "0.7.1"
spl-token-metadata-interface = "0.8.0"
spl-token-2022-interface = "2.0.0"
# End
thiserror = "2.0.17"
tokio = "1.48.0"
toml = "0.9.8"
yellowstone-shield = { path = "program" }
yellowstone-shield-cli = { path = "cli", version = "0.7.0" }
yellowstone-shield-parser = { path = "parser", version = "0.7.0" }
yellowstone-grpc-client = "10.1.0"
yellowstone-grpc-proto = "10.1.0"

[workspace.metadata.toolchains]
format = "1.86"
lint = "1.86"

[workspace.metadata.cli]
solana = "3"

[workspace.lints.clippy]
clone_on_ref_ptr = "deny"
missing_const_for_fn = "deny"
trivially_copy_pass_by_ref = "deny"
