[package]
name = "yellowstone-shield-client"
version = "0.0.0"
description = "A generated Rust library for the Blocklist program"
repository = "https://github.com/rpcpool/yellowstone-shield"
edition = "2021"
readme = "README.md"
license-file = "../../LICENSE"

[features]
test-sbf = []
anchor = ["dep:anchor-lang"]
serde = ["dep:serde", "dep:serde_with"]

[dependencies]
anchor-lang = { version = "0.31.0", optional = true }
borsh = "^0.10"
num-derive = "^0.3"
num-traits = "^0.2"
serde = { version = "^1.0", features = ["derive"], optional = true }
serde_with = { version = "^3.0", optional = true }
solana-program = "2.1.11"
solana-sdk = "2.1.11"
spl-token-2022 = { version = "7", features = ["no-entrypoint"] }
thiserror = "^1.0"
spl-associated-token-account = { version = "6", features = ["no-entrypoint"] }
spl-token-metadata-interface = { version = "0.6" }
spl-pod = "0.5"

[dev-dependencies]
assert_matches = "1.5.0"
solana-program-test = "2.1.11"
